### ISSUE TITLE
Question: Will New Filters from QSVEnc, NVEnc, and VCEEnc Be Implemented in Aviutl-clcufilters?

### ISSUE THREAD

**Issue by quamt** [rigaya/Aviutl-clcufilters#3]
@rigaya

First, I am grateful for your continuous development of Aviutl-clcufilters and the related encoding tools.

I have a question regarding the newly introduced filters in QSVEnc, NVEnc, and VCEEnc—filters such as lib-placebo and FFT3D, for example. I was wondering if there are any plans to incorporate these or similar filters into Aviutl-clcufilters.

The real-time preview feature in Aviutl with the Aviutl-clcufilters is a fantastic tool. It makes it much easier to see the effects of different filters and fine-tune settings efficiently. It would significantly enhance the workflow by allowing users to maintain consistency across tools while benefiting from the immediate visual feedback that Aviutl provides.

I would appreciate any information you could share if you have any considerations or plans for adding the new filters.

Thank you for your time and for all the effort you put into improving the Aviutl-clcufilters

**Comment by rigaya** [comment]
There are plans for adding some new filters to Aviutl-clcufilters, like adding libplacebo filters.

But there are limitation - temporal filters such as FFT3D, colvolution3D, ... will not be added.

This is because of implementation limitation (which I have written in [readme](https://github.com/rigaya/Aviutl-clcufilters#%E8%AA%B2%E9%A1%8C) (but in Japanese...)). Aviutl allows parameters to be changed between frames, but it will be difficult to support this in 3D filters with design of Aviutl-clcufilters.

Also, I must say that the priority of Aviutl-clcufilters is low, I am likely to first work on other encoder related stuff, so I will not be able to say when they will be added. (Although the filter itself can be copied from the encoder, creating UI takes many time for me...)

**Comment by quamt** [comment]
Thank you for taking the time to explain the situation. I understand that implementing FFT3D may not be feasible at this point, and I appreciate that the focus is currently on improving the encoders, which is crucial for the project’s progress.

I will be closing this ticket.
